# Generated by Django 5.1.1 on 2024-09-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dn9l0cxcv/image/upload/v1727030272/pp5-walkthrough/botfh2hlxd6cudukcqj6.jpg', upload_to='images/pp5-walkthrough-profile'),
        ),
    ]
